# Generated by Django 5.2.2 on 2025-06-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='service',
            name='servico',
        ),
        migrations.AddField(
            model_name='service',
            name='descricao',
            field=models.CharField(default='Descreva sua empresa', max_length=100, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('servicos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='plataforma.service', verbose_name='Serviços')),
            ],
        ),
    ]
