# Generated by Django 5.2.3 on 2025-06-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_service_especialidades_remove_service_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Serviço'),
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
