# Generated by Django 5.2.3 on 2025-06-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_remove_service_localizacao_service_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
